common: &aws_iot
  root_ca_path: ../root-CA.crt
  endpoint: a1pxxd60vwqsll.iot.ap-southeast-2.amazonaws.com

gas_sensor:
  aws_iot:
    <<: *aws_iot
    certificate_path: ../40stokesMCP.cert.pem
    private_key_path: ../40stokesMCP.private.key
    client_id: 40stokesMCP
  mcp9000:
    bus: 1
    address: 0x63
  log_level: DEBUG

heatpump_controller:
  aws_iot:
    <<: *aws_iot
    certificate_path: ../40stokesDHT.cert.pem
    private_key_path: ../40stokesDHT.private.key
    client_id: 40stokesDHT
  dht:
    data_pin: 22
    onoff_pin: 18
  led_verify:
    le_pin: 25
    d0_pin: 17
    q0_pin: 24
  default_setpoints:
    heating_start: 16
    heating_stop: 18
    cooling_stop: 22
    cooling_start: 24
  log_level: DEBUG
  gas_sensor:
    client_id: 40stokesMCP
    threshold: 40
